import OpenAI from "openai";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";
import 'dotenv/config';

function parseLLMJson(rawText) {
  if (!rawText) {
    throw new Error("Received empty or null response from LLM.");
  }

  // 1. Strip markdown fences
  let cleaned = rawText.replace(/```json/gi, "").replace(/```/g, "").trim();

  // 2. Extract strictly from the first '{' to the last '}'
  const firstBrace = cleaned.indexOf("{");
  const lastBrace = cleaned.lastIndexOf("}");

  if (firstBrace !== -1 && lastBrace !== -1) {
    cleaned = cleaned.slice(firstBrace, lastBrace + 1);
  }

  try {
    return parseLLMJson(cleaned);
  } catch (err) {
    console.error("❌ RAW LLM OUTPUT THAT FAILED TO PARSE:\n", rawText);
    throw err;
  }
}

// 1. Define separate configurations for Planner vs Coder
const PLANNER_CONFIG = {
  baseURL: process.env.PLANNER_BASE_URL || "http://localhost:11434/v1", // e.g., local Ollama / vLLM
  apiKey: process.env.PLANNER_API_KEY || "ollama",
  model: process.env.PLANNER_MODEL || "qwen2.5-coder:7b",
};

const CODER_CONFIG = {
  baseURL: process.env.CODER_BASE_URL || "https://api.openai.com/v1", // e.g., large provider / GPT-4o
  apiKey: process.env.CODER_API_KEY || "sk-...",
  model: process.env.CODER_MODEL || "gpt-4o",
};

// Instantiates client dynamically depending on task
function getClient(config) {
  return new OpenAI({ baseURL: config.baseURL, apiKey: config.apiKey });
}

async function ideateProject() {
  console.log(`\n💡 [0/5] Auto-generating project ideas with SMALL Model...`);

  const ideationPrompt = `Generate a creative, highly useful, self-contained Node.js CLI or utility tool idea.
Requirements:
1. Must be buildable within a single Node.js workspace.
2. Must have clear input/output and be easily testable using native node:test or Jest.
3. Should solve a real developer, file-management, or productivity problem (e.g., log parsing, format converters, API mock servers, file bundlers).

Respond strictly in JSON format matching this schema:
{
  "title": "Short Project Title",
  "summary": "1-sentence description of the tool",
  "goalPrompt": "Detailed prompt describing the core logic, CLI interface, and expected test cases."
}`;

  // Use the fast/small PLANNER_CONFIG model to brainstorm
  const rawIdeaJson = await askLLM(PLANNER_CONFIG, ideationPrompt, "You are a Product Manager specializing in developer tools.", true);
  const idea = parseLLMJson(rawIdeaJson);

  console.log(`✨ Selected Idea: "${idea.title}"`);
  console.log(`📝 Description: ${idea.summary}`);

  return idea.goalPrompt;
}

function runCommand(command, cwd = process.cwd()) {
  try {
    const stdout = execSync(command, { cwd, encoding: "utf8", stdio: "pipe" });
    return { success: true, output: stdout };
  } catch (error) {
    return {
      success: false,
      output: (error.stdout || "") + "\n" + (error.stderr || "") + "\n" + error.message,
    };
  }
}

async function askLLM(config, prompt, systemInstruction = "", jsonMode = false) {
  const client = getClient(config);
  const messages = [];
  if (systemInstruction) messages.push({ role: "system", content: systemInstruction });
  messages.push({ role: "user", content: prompt });

  const response = await client.chat.completions.create({
    model: config.model,
    messages,
    ...(jsonMode ? { response_format: { type: "json_object" } } : {}),
  });

  return response.choices[0].message.content;
}

async function runMultiModelLoop(userGoal) {
  const projectDir = path.join(process.cwd(), "generated-project");
  if (fs.existsSync(projectDir)) fs.rmSync(projectDir, { recursive: true, force: true });
  fs.mkdirSync(projectDir, { recursive: true });

  // STEP 1: Small Model generates the SPEC
  console.log(`\n🧠 [1/5] Using SMALL Model (${PLANNER_CONFIG.model}) to design SPEC.md...`);
  const specPrompt = `Create a clear SPEC.md for a Node.js project: "${userGoal}".
Include: Project Title, required files (package.json, index.js, test file using node:test), and execution steps.`;

  const specContent = await askLLM(PLANNER_CONFIG, specPrompt, "You are a Software Architect.");
  fs.writeFileSync(path.join(projectDir, "SPEC.md"), specContent);
  console.log("✅ SPEC.md generated by planner model.");

  // STEP 2: Large Model generates the source code based on SPEC.md
  console.log(`\n⚡ [2/5] Using LARGE Model (${CODER_CONFIG.model}) to write source code...`);
  const codePrompt = `Based on this SPEC:\n\n${specContent}\n\n
Generate all initial project files. Ensure 'package.json' includes "test": "node --test".
Respond strictly with a JSON object:
{
  "files": [
    { "filePath": "package.json", "content": "..." },
    { "filePath": "index.js", "content": "..." }
  ]
}`;

  const rawFilesJson = await askLLM(CODER_CONFIG, codePrompt, "You are a Senior Software Engineer.", true);
  const parsed = parseLLMJson(rawFilesJson);
  const files = parsed.files || parsed;

  for (const file of files) {
    const fullPath = path.join(projectDir, file.filePath);
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, file.content);
    console.log(`  - Wrote ${file.filePath}`);
  }

  // STEP 3: Install Dependencies
  console.log("\n⚙️ [3/5] Installing npm dependencies...");
  runCommand("npm install", projectDir);

  // STEP 4: Test & Debug Loop using LARGE Model
  console.log(`\n🧪 [4/5] Running test & debug loop with LARGE Model (${CODER_CONFIG.model})...`);
  const MAX_REPAIR_ATTEMPTS = 5;
  let passed = false;

  for (let attempt = 1; attempt <= MAX_REPAIR_ATTEMPTS; attempt++) {
    const testRun = runCommand("npm test", projectDir);
    if (testRun.success) {
      console.log("✅ Tests PASSED!");
      passed = true;
      break;
    }

    console.log(`❌ Attempt ${attempt} failed. Debugging with ${CODER_CONFIG.model}...`);
    const currentFiles = files.map((f) => {
      const p = path.join(projectDir, f.filePath);
      return { filePath: f.filePath, content: fs.existsSync(p) ? fs.readFileSync(p, "utf8") : "" };
    });

    const debugPrompt = `Tests failed (\`npm test\`):\n${testRun.output}\n
Current Workspace:\n${JSON.stringify(currentFiles, null, 2)}\n
Fix all issues and return updated JSON under key "files".`;

    const rawFixes = await askLLM(CODER_CONFIG, debugPrompt, "You are a debugging expert.", true);
    const fixedFiles = (parseLLMJson(rawFixes)).files;

    for (const file of fixedFiles) {
      fs.writeFileSync(path.join(projectDir, file.filePath), file.content);
      console.log(`  - Repaired ${file.filePath}`);
    }
  }

  if (!passed) process.exit(1);

  // STEP 5: Release
  console.log("\n🌐 [5/5] Publishing repository to GitHub...");
  const repoName = `vibe-${Date.now()}`;
  const targetOrg = process.env.GITHUB_ORG?.trim();

  runCommand("git init", projectDir);
  runCommand("git add .", projectDir);
  runCommand(`git commit -m "feat: autonomous release by VibeVibes"`, projectDir);

  // Build gh repo create command dynamically
  const orgFlag = targetOrg ? `--org ${targetOrg}` : "";
  const ghRepoCreate = runCommand(
    `gh repo create ${targetOrg ? `${targetOrg}/` : ""}${repoName} ${orgFlag} --public --source=. --remote=origin --push`,
    projectDir
  );

  if (!ghRepoCreate.success) {
    console.error("Failed to create GitHub repository:\n", ghRepoCreate.output);
    return;
  }

  const releaseRun = runCommand(
    `gh release create v1.0.0 --notes "Automated build and release by VibeVibes."`,
    projectDir
  );

  if (releaseRun.success) {
    const owner = targetOrg || runCommand("gh api user -q .login", projectDir).output.trim();
    console.log(`🎉 Success! Repo live at: https://github.com/${owner}/${repoName}`);
  }
}


async function main() {
  goal = await ideateProject();

  await runMultiModelLoop(goal);
}

main().catch(console.error);
